# Generated by Django 3.1.4 on 2020-12-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201221_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='product',
        ),
        migrations.AddField(
            model_name='tag',
            name='products',
            field=models.ManyToManyField(to='products.Product'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img_file',
            field=models.ImageField(upload_to='images', verbose_name='Image'),
        ),
    ]
