# Generated by Django 3.1.4 on 2020-12-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201226_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
