# Generated by Django 3.1.4 on 2021-03-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20210301_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(default='images/default_sub_category.jpg', upload_to='images'),
        ),
    ]
